### ISSUE TITLE
Make sure MapMap still works on Ubuntu 14.04

### ISSUE THREAD

**Issue by aalex** [mapmapteam/mapmap#193]
ConsoleWindow.cpp:35:39: error: ‘Medium’ is not a member of ‘QFont’
     QFont font(QFont(":/base-font", 10, QFont::Medium));
                                       ^
  compilation terminated due to -Wfatal-errors.
  make: *** [ConsoleWindow.o] Erreur 1

**Comment by aalex** [comment]
We should have ifdef macros checking for Qt version before using new features that are not supported in older versions of Qt.

**Comment by sofian** [comment]
True. Although 16.04 LTS is coming up next month and uses Qt 5.5 so we might also use the opportunity to enforce switching to 16.04.

**Comment by baydam** [comment]
Alex is also right. We can put the macro for checking Qt version

**Comment by sofian** [comment]
Yes. That means that someone needs to keep a version of ubuntu 14.04 for backwards testing.

**Comment by aalex** [comment]
I can take care of that. At the school where I give workshops, we use 14.04. The next class is Thursday.

**Comment by aalex** [comment]
Does this work for you? https://github.com/mapmapteam/mapmap/commit/1708311fd8c04fbce049c0634b33465603250264

**Comment by sofian** [comment]
Ça compile et ça roule sur Qt 5.5 (Ubuntu 15.10).

**Comment by aalex** [comment]
Fixed in 948c27e6bb856c616bec6fbd9d2584ef50767621
