### ISSUE TITLE
Cannot compile on OSX... Issue with QtAbstractPropertyBrowserPrivate

### ISSUE THREAD

**Issue by ltsadair** [mapmapteam/mapmap#368]
ran git bisect already, below are the first four errors:

```
src/app/mocs/moc_qtpropertybrowser.cpp:363:29: error: member access into incomplete type 'QtAbstractPropertyBrowserPrivate'
        case 4: _t->d_func()->slotPropertyInserted((*reinterpret_cast< QtProperty*(*)>(_a[1])),(*reinterpret_cast< QtProperty*(*)>(_a[2])),(*reinterpret_cast< QtProperty*(*)>(_a[3]))); break;
                            ^
src/app/mocs/../../gui/contrib/qtpropertybrowser/src/qtpropertybrowser.h:263:18: note: forward declaration of 'QtAbstractPropertyBrowserPrivate'
    friend class QtAbstractPropertyBrowserPrivate;
                 ^
src/app/mocs/moc_qtpropertybrowser.cpp:364:29: error: member access into incomplete type 'QtAbstractPropertyBrowserPrivate'
        case 5: _t->d_func()->slotPropertyRemoved((*reinterpret_cast< QtProperty*(*)>(_a[1])),(*reinterpret_cast< QtProperty*(*)>(_a[2]))); break;
                            ^
src/app/mocs/../../gui/contrib/qtpropertybrowser/src/qtpropertybrowser.h:263:18: note: forward declaration of 'QtAbstractPropertyBrowserPrivate'
    friend class QtAbstractPropertyBrowserPrivate;
                 ^
src/app/mocs/moc_qtpropertybrowser.cpp:365:29: error: member access into incomplete type 'QtAbstractPropertyBrowserPrivate'
        case 6: _t->d_func()->slotPropertyDestroyed((*reinterpret_cast< QtProperty*(*)>(_a[1]))); break;
                            ^
src/app/mocs/../../gui/contrib/qtpropertybrowser/src/qtpropertybrowser.h:263:18: note: forward declaration of 'QtAbstractPropertyBrowserPrivate'
    friend class QtAbstractPropertyBrowserPrivate;
                 ^
src/app/mocs/moc_qtpropertybrowser.cpp:366:29: error: member access into incomplete type 'QtAbstractPropertyBrowserPrivate'
        case 7: _t->d_func()->slotPropertyDataChanged((*reinterpret_cast< QtProperty*(*)>(_a[1]))); break;
                            ^
src/app/mocs/../../gui/contrib/qtpropertybrowser/src/qtpropertybrowser.h:263:18: note: forward declaration of 'QtAbstractPropertyBrowserPrivate'
    friend class QtAbstractPropertyBrowserPrivate;
```

Attached is the log.

[gitbisectlog.txt](https://github.com/mapmapteam/mapmap/files/1515520/gitbisectlog.txt)

**Comment by sofian** [comment]
@baydam @aalex This compilation error was introduced in April by one of you guys. Could you please look into it? @ltsadair is working on Syphon integration (!) but this is blocking him cause he cannot compile on Mac.

```
commit 58ae7b474df27cc5a2bb3c7a20d3c0adead264e7
Author: baydam <baydamd@gmail.com>
Date:   Tue Aug 1 01:45:13 2017 +0000

    Ignore mocs, obj and qrc directory

commit bbdb002af2a7f1a2feeb68a0d3199e97b40bcf90
Author: Alexandre Quessy <alexandre@quessy.net>
Date:   Sun Apr 16 20:50:36 2017 -0400

    Move files to src/mapmap

commit 8514766eb8149822ab948e1d94a290b01ecd13af
Author: Alexandre Quessy <alexandre@quessy.net>
Date:   Sun Apr 16 20:05:51 2017 -0400

    Mouse wheel: press control to zoom. WIP: scroll
```

**Comment by sofian** [comment]
@ltsadair is running macOs 10.13 so it might be related to that (I think MapMap has been tested/compiled on 10.11 last).

**Comment by ltsadair** [comment]
Thanks, however still getting an error rooting from.
```
error: member access into incomplete type 'QtAbstractPropertyBrowserPrivate'
```

**Comment by aalex** [comment]
It was probably introduced when we moved around the files. This seems to be high priority.

**Comment by sofian** [comment]
The problem is related to the fact that some classes (eg. QtAbstractPropertyBrowserPrivate) are being declared in qtpropertybrowser.h but are actually defined and implemented in qtpropertybrowser.cpp. Which is unusual, but works if you compile things in a certain way.

**Comment by sofian** [comment]
However with the changes introduced by commits 58ae7b474df27cc5a2bb3c7a20d3c0adead264e7, bbdb002af2a7f1a2feeb68a0d3199e97b40bcf90 and/or 8514766eb8149822ab948e1d94a290b01ecd13af, this process got de-coupled and the compiler cannot find the declaration and implementation (I guess cause it is just including the .h, where the type is incomplete).

**Comment by sofian** [comment]
@aalex @baydam We are not going to be able to move forward until this bug is fixed. This is blocking and critical.

**Comment by baydam** [comment]
What version of Qt do you Lucas. I suggest to do a fresh clone and try again

**Comment by sofian** [comment]
I don't think this is the issue. I have the same problem on Ubuntu with an updated version of Qt. See #367. The problem is not related to At but to the build process. See my comments on this issue.

**Comment by sofian** [comment]
Ok so good news: I *was* able to compile using a fresh clone! I'm on Ubuntu 17.10, Qt version 5.6.0

**Comment by baydam** [comment]
Try the same on OSX

**Comment by sofian** [comment]
Will do.

**Comment by sofian** [comment]
I was able to fix this issue by simply checking out a fresh version of MapMap from the github.
git clone -b develop git@github.com:mapmapteam/mapmap
